# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/ryfon/Documents/Code/comp/ECE369/Lab_4/frank2022/frank2022.runs/synth_1/WinRARTop.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 4
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/ryfon/Documents/Code/comp/ECE369/Lab_4/frank2022/frank2022.cache/wt [current_project]
set_property parent.project_path C:/Users/ryfon/Documents/Code/comp/ECE369/Lab_4/frank2022/frank2022.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/ryfon/Documents/Code/comp/ECE369/Lab_4/frank2022/frank2022.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_mem {
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem32.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem40.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem59.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem24.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/data_memory.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem42.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem16.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem30.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem34.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem8.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem18.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem22.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/test1_instr.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem36.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem2.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem49.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem45.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/instruction.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem28.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem11.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem1.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem54.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem37.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem47.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem60.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem4.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem64.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem13.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/data.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem26.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem51.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem43.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem56.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem39.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem62.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem6.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem15.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem58.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem7.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem33.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem17.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem25.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem9.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem21.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem48.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem35.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem3.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem19.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem41.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem53.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem23.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem10.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem61.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem52.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem20.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem38.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem55.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem46.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem0.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem12.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem29.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem50.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem5.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem27.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem14.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem63.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem57.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem44.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Mem31.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/InstrMem0.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/InstrMem1.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/InstrMem3.mem
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/InstrMem2.mem
}
read_verilog -library xil_defaultlib {
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/ALUSetup.v
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/ALUFinalStage.v
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/ALUAdderStage.v
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/FullAdder2Bit.v
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/18StageALU.v
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/ALUController.v
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/MUXController.v
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/MemController.v
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/RegisterFile.v
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Decode.v
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/SignExtension.v
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Execute.v
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/InstructionMemory.v
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/PCAdder.v
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/ProgramCounter.v
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Fetch.v
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/InstrMemStage.v
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/InstructionMemoryAccess.v
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/InstructionMemoryParse.v
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/FetchTop.v
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/MemAccess.v
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/MemParse1.v
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/MemParse2.v
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/SevenSegment.v
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/ThreeStageMem.v
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/Two4DigitDisplay.v
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/WriteBack.v
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/WinRAR.v
  C:/Users/ryfon/Documents/Code/comp/ECE369/src/Verilog/WinRARTop.v
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/ryfon/Documents/Code/comp/ECE369/src/xdc_files/Two4DigitDisplay.xdc
set_property used_in_implementation false [get_files C:/Users/ryfon/Documents/Code/comp/ECE369/src/xdc_files/Two4DigitDisplay.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Users/ryfon/Documents/Code/comp/ECE369/Lab_4/frank2022/frank2022.srcs/utils_1/imports/synth_1/WinRARTop.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top WinRARTop -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef WinRARTop.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file WinRARTop_utilization_synth.rpt -pb WinRARTop_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
