@echo off
REM ****************************************************************************
REM Vivado (TM) v2022.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sat Dec 07 14:15:38 -0700 2024
REM SW Build 3671981 on Fri Oct 14 05:00:03 MDT 2022
REM
REM IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim WinRAR_tb_func_impl -key {Post-Implementation:sim_1:Functional:WinRAR_tb} -tclbatch WinRAR_tb.tcl -view C:/Users/ryfon/Documents/Code/comp/ECE369/Lab_4/frank2022/WinRAR_tb_behav.wcfg -log simulate.log"
call xsim  WinRAR_tb_func_impl -key {Post-Implementation:sim_1:Functional:WinRAR_tb} -tclbatch WinRAR_tb.tcl -view C:/Users/ryfon/Documents/Code/comp/ECE369/Lab_4/frank2022/WinRAR_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
